apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-locker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resource-locker-operator
  template:
    metadata:
      labels:
        name: resource-locker-operator
    spec:
      serviceAccountName: resource-locker-operator
      containers:
        - name: resource-locker-operator
          # Replace this with the built image name
          image: quay.io/redhat-cop/resource-locker-operator:v0.1.0
          command:
          - resource-locker-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace                  
            - name: OPERATOR_NAME
              value: "resource-locker-operator"
